<a href="https://colab.research.google.com/github/mariotlemes/pos-NLP/blob/main/python_para_processamento_de_dados.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Código 1 - Verificando a instalação do NumPy

In [ ]:
!pip install numpy

In [ ]:
import numpy as np
print("A versão do NumPy é", np.__version__)

A versão do NumPy é 2.0.2


Código 2 - Exemplos de utilização da biblioteca NumPy com arrays unidimensionais


In [ ]:
# array de uma dimensão
a = np.array([1, 2, 3, 4, 5])
print("Array a =", a)

# operação matemática simples
b = a * 2
print("Array b =", b)

Array a = [1 2 3 4 5]
Array b = [ 2  4  6  8 10]


Código 3 - Exemplos de utilização da biblioteca NumPy com arrays multidimensionais e funções

In [ ]:
c = np.array([[1,2], [3,4]])
print("Matriz:\n", c)

print("\n")

# soma simples em cada número da matriz
d = c + 3
print("Matriz d:\n", d)

print("\n")

# calcular a media dos elementos do array a
media  = np.mean(a)
print("A média dos elementos do array a é:", media)

Matriz:
 [[1 2]
 [3 4]]


Matriz d:
 [[4 5]
 [6 7]]


A média dos elementos do array a é: 3.0


Código 4 - Exemplo de criação de um array a partir de uma lista

In [ ]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
print("Array a:", a)

Array a: [1 2 3 4 5]


Código 5 - Criando array de zeros com np.zeros

In [ ]:
zeros_array = np.zeros((3,3))
print("Matriz de zeros 3x3:\n", zeros_array)

Matriz de zeros 3x3:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Código 6 - Exemplo de utilização da função np.arange

np.arrange(start, stop, step): usada para criar arrays com valores sequenciais

In [ ]:
import numpy as np

range_array = np.arange(0, 10, 2)
print("O array é:", range_array)

O array é: [0 2 4 6 8]


Código 7 - Exemplo de utilização da função np.linspace

np.linspace(start, stop, num): cria arrays com valores espaçados uniformemente em um intervalo

In [ ]:
import numpy as np

linspace_array = np.linspace(0, 1, 5)
print("O array é:", linspace_array)


O array é: [0.   0.25 0.5  0.75 1.  ]


Código 8 - Atributos shape e ndim de um array NumPy

In [ ]:
import numpy as np

linspace_array = np.linspace(0, 1, 5)
print("Array:", linspace_array)
print("Forma do array:", linspace_array.shape)
print("Número de dimensões:", linspace_array.ndim)


Array: [0.   0.25 0.5  0.75 1.  ]
Forma do array: (5,)
Número de dimensões: 1


Código 9 - Exemplo de criação de array multidimensional (matriz 2x3) a partir de listas

In [ ]:
import numpy as np

matriz = np.array([[1, 2, 3], [4, 5, 6]])
print("Matriz 2x3:\n", matriz)

Matriz 2x3:
 [[1 2 3]
 [4 5 6]]


Código 10 - Exemplo de utilização do atributo dtype de um array do NumPy

In [ ]:
import numpy as np

matriz = np.array([[1, 2, 3], [4, 5, 6]])
print("O tipo de dados da matriz é:", matriz.dtype)

O tipo de dados da matriz é: int64


Código 11 - Alterando o valor da posição 0 de um array previamente definido

In [ ]:
import numpy as np

array_a = ([1, 2, 3, 4, 5])
array_a[0] = 10
print("O novo array a é:", array_a)

O novo array a é: [10, 2, 3, 4, 5]


Código 12 - Exemplos com listas (mutável), tuplas (imutável) e sets (não ordenado e sem duplicatas)

In [ ]:
import numpy as np

lista = [1, "dois", 3.0]

print("A lista mista é:", lista)

# adicionando um novo membro
lista.append(4)
print("A lista com append é:", lista)

tupla = (1, 2, 3)
print("O valor da tupla é:", tupla)

# não é possível
# tupla[0] = 2

conjunto  = {1, 2, 3, 3}
print("O valor do conjunto (não mostra valores duplicados) é:", conjunto)

A lista mista é: [1, 'dois', 3.0]
A lista com append é: [1, 'dois', 3.0, 4]
O valor da tupla é: (1, 2, 3)
O valor do conjunto (não mostra valores duplicados) é: {1, 2, 3}


Código 13 - Comparando o tempo de execução entre listas e arrays do NumPy

In [ ]:
import numpy as np
import time

lista = list(range(1000000))
inicio = time.time()
lista = [valor + 1 for valor in lista]
fim = time.time()
print("Tempo de processamento com lista é:", fim - inicio)

array = np.arange(1000000)
inicio2 = time.time()
array += 1
fim2 = time.time()
print("Tempo de processamento com array é:", fim2 - inicio2)

Tempo de processamento com lista é: 0.05792045593261719
Tempo de processamento com array é: 0.0010159015655517578


Código 14 - Exemplo de operações aritméticas com arrays

In [ ]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5 , 6])

print("O valor do array a + array b é: ", a + b)
print("O valor do array a - b é: ", a - b)
print("O valor de multiplicação do array a por b é:",  a * b)
print("A divisão do array a por b é:", a / b)


O valor do array a + array b é:  [5 7 9]
O valor do array a - b é:  [-3 -3 -3]
O valor de multiplicação do array a por b é: [ 4 10 18]
A divisão do array a por b é: [0.25 0.4  0.5 ]
